# Generated by Django 4.2.7 on 2025-11-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='cadastros.usuario'),
        ),
    ]
